### ISSUE TITLE
schema locations

### ISSUE THREAD

**Issue by davidelbert** [imqcam/uploader#1]
Hi Maggie.  I've had so little time to talk the last few weeks that I thought I'd toss an idea here as an "issue".  I am thinking that the schemas for metadata input belong in their own repo and not as a part of uploader code.  Here's my thinking.  See if you agree or if I am missing something.  Basically, these schema are the source for forms in IMQCAM and all those forms end up in one place and it seems natural that people would want to find the schema to see what they capture and to potentially update them or use them as a helper to create a new schema.  At the moment, these are used to capture data associated with the uploader you are working on so it has seemed natural to put them in the repo capturing that uploader work, but there is no reason that any given metadata form is only associated with an uploader.  One can imagine, for example, that some are used only for things that people manually upload (likely the case for powder forms actually) or in cases that end up with streaming. One can imagine the need to describe the semantics of things that are being described across the STRI completely separate from the application of those schema in a tool like an uploader, in which case it makes sense to have all the schema together but the current system would put them in different repos depending on what is using them.  In one way, I think of them as a type of asset so something that should be filed with others of the same type.  If they are stored in different places then the only way to know they exist or find them is to have the insider knowledge of the person who made them (and they are harder to find as the scale of things grows).  Right now I fall prey to that and end up searching or having to ask you like I did last week.

On the downside, I suppose is that having them in the same repo as the code is the easiest way to access them when you pull the repo and with the tool that uses them.  To get around that would take a little thinking but I don't think it would take a major tool or registry.  Thoughts?

Thoughts?

**Comment by eminizer** [comment]
Sure, I can put them in a different repo if you'd like. I'll start a new one just for the schema files today.

**Comment by davidelbert** [comment]
Thanks.  I think that's better. Sorry my "issue" was so long winded!  The less time I have the longer my communications. 🤦‍♂️
